name: petzone_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7
  table_calendar: ^3.0.9
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.16.0
  http: ^1.3.0
  provider: ^6.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/






flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Logo.jpg
  android_12:
    image: assets/images/Logo.jpg
    color: "#ffffff"
    android_gravity: center